name: netflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animations: ^2.0.11
  bordered_text: ^2.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  liquid_pull_to_refresh: ^3.0.1
  palette_generator: ^0.3.3+3
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  video_player: ^2.8.6

dev_dependencies:
  build_runner: ^2.4.10

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/netflixLogo.png
