name: netflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bordered_text: ^2.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  palette_generator: ^0.3.3+3
  video_player: ^2.8.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/netflixLogo.png
